global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'user-service'
    static_configs:
      - targets: ['hotstar-user-service:5002']

  - job_name: 'auth-service'
    static_configs:
      - targets: ['hotstar-auth-service:5001']

  - job_name: 'video-service'
    static_configs:
      - targets: ['hotstar-video-service:5003']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['hotstar-api-gateway:5000']

  - job_name: 'streaming-service'
    static_configs:
      - targets: ['hotstar-streaming-service:5005']

  - job_name: 'notification-service'
    static_configs:
      - targets: ['hotstar-notification-service:5006']

  - job_name: 'frontend'
    static_configs:
      - targets: ['hotstar-frontend:3000']
